M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu24.04.1} date 2024-10-24T15:12:12+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-24T15:12:12+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.0189Y-2.0193
X4.4007Y-3.2637
M30
